language: php

php:
 - 7.0
 - 7.1

mysql:
  database: phpple
  username: root
  charset: utf8

before_script:
  - composer install
  - mysql -e "create database phpple"
  - mysql < ./test/init.sql

script: phpunit -v
