language: php

php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

mysql:
  database: phpple
  username: phpple
  password: phpple
  charset: utf8

before_script:
  - composer install
  - mysql -e "create database phpple"
  - mysql < ./test/u_user.sql

script: phpunit -v
