language: php

php:
 - 7.0
 - 7.1

mysql:
  database: phpple
  username: root
  charset: utf8

before_script:
  - composer install
  - mysql -e "create database phpple"
  - mysql < ./tests/init.sql
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
